export const LOAD_POPULAR_SHOWS_SUCCESS = 'LOAD_SHOWS_SUCCESS';
export const LOAD_TODAYS_SHOWS_SUCCESS = 'LOAD_TODAYS_SHOWS_SUCCESS';
export const LOAD_SHOW_DETAILS_SUCCESS = 'LOAD_SHOW_DETAILS_SUCCESS';
export const ADD_SHOW = 'ADD_SHOW';

export const LOAD_PERSON_SUCCESS = 'LOAD_PERSON_SUCCESS';

export const LOAD_MOVIE_DETAILS_SUCCESS = 'LOAD_MOVIE_DETAILS_SUCCESS';
export const LOAD_POPULAR_MOVIES_SUCCESS = 'LOAD_POPULAR_MOVIES_SUCCESS';
export const LOAD_UPCOMING_MOVIES_SUCCESS = 'LOAD_UPCOMING_MOVIES_SUCCESS';
export const ADD_CREDITS_TO_MOVIE = 'ADD_CREDITS_TO_MOVIE';
export const ADD_YOUTUBE_ID_TO_MOVIE = 'ADD_YOUTUBE_ID_TO_MOVIE';
export const LOAD_SUGGESTED_MOVIES = 'LOAD_SUGGESTED_MOVIES';
export const LOAD_BOX_OFFICE_MOVIES = 'LOAD_BOX_OFFICE_MOVIES';

export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_RESET = 'SEARCH_RESET';
export const SEARCH_NEXT_PAGE = 'SEARCH_NEXT_PAGE';
export const SEARCH_PREV_PAGE = 'SEARCH_PREV_PAGE';
export const SEARCH_CHANGE_FILTER = 'SEARCH_CHANGE_FILTER';
