export const LOAD_SHOWS_SUCCESS = "LOAD_SHOWS_SUCCESS";
export const LOAD_SHOW_DETAILS_SUCCESS = "LOAD_SHOW_DETAILS_SUCCESS";
export const ADD_SHOW = "ADD_SHOW";

export const LOAD_PERSON_SUCCESS = "LOAD_PERSON_SUCCESS";

export const LOAD_MOVIE_DETAILS_SUCCESS = "LOAD_MOVIE_DETAILS_SUCCESS";
export const LOAD_POPULAR_MOVIES_SUCCESS = "LOAD_POPULAR_MOVIES_SUCCESS";
export const LOAD_UPCOMING_MOVIES_SUCCESS = "LOAD_UPCOMING_MOVIES_SUCCESS";
export const ADD_CREDITS_TO_MOVIE = "ADD_CREDITS_TO_MOVIE";